plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  
remote_theme: "mmistakes/minimal-mistakes@4.14.1"

---
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
      toc_label: "My Table of Contents"
      toc_icon: "cog"
---
